trigger:
  - master

variables:
  imageName: 'elevation-of-privilege'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:      
- stage: Build
  displayName: Build and Push
  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: ./Dockerfile
        containerRegistry: preagendamiento-cr

- stage: Deploy_Dev
  displayName: Deploy Dev
  jobs:
    
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
          appType: 'webAppContainer'
          WebAppName: 'elevation-of-privilege'
          DockerNamespace: 'preagendamiento.azurecr.io'
          DockerRepository: 'elevation-of-privilege'
          DockerImageTag: '$(tag)'